### ISSUE TITLE
Todo-List before ordering

### ISSUE THREAD

**Issue by obehr** [obehr/phoniebox_hat#1]
The following things should be done before ordering the PCB:

- [ ] Check compliance to Raspberry Pi HAT [specification](https://github.com/raspberrypi/hats)
- [ ] Verify battery disconnect circuit function (prototype and/or simulation)
- [ ] Check DAC circuit according to datasheet / typical application
- [ ] Check Amplifier circuit according to datasheet / typical application
- [ ] Connection of DAC and Amp - will it work like this?
- [ ] Filter size for button debouncing ok or too big?
- [ ] Confirm USB-C connection. Does it allow to draw 3A @ 5V?
